#!/bin/bash

{
    set -ex

    EXT_IFACE=eth0
    XINETD_LISTEN_PORT=22
    HOSTNAME=$(/bin/hostname)

    MEM_LIMIT=128M
    QUOTA_IN=5242880
    QUOTA_OUT=1310720

    # fix REMOTE_HOST to only contain IP address
    REMOTE_HOST=${REMOTE_HOST//::ffff:/}
    export REMOTE_HOST

    IMAGE_NAME=honeypot
    CNM="${IMAGE_NAME}-${REMOTE_HOST}"

    # avoid locale assertion with nsenter
    export LC_ALL=C

    # check if the container exists
    if ! docker inspect "${CNM}" &> /dev/null; then
        # create new container
        CID=$(docker run --name "${CNM}" -h "${HOSTNAME}" -e "REMOTE_HOST=${REMOTE_HOST}" -m ${MEM_LIMIT} -d ${IMAGE_NAME})
        CIP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "${CID}")
        PID=$(docker inspect --format '{{ .State.Pid }}' "${CID}")

        # drop all inbound and outbound traffic by default
        nsenter --target "${PID}" -n iptables -P INPUT DROP
        nsenter --target "${PID}" -n iptables -P OUTPUT DROP

        # allow access to the service regardless of the quota
        nsenter --target "${PID}" -n iptables -A INPUT -p tcp -m tcp --dport ${XINETD_LISTEN_PORT} -j ACCEPT
        nsenter --target "${PID}" -n iptables -A INPUT -m quota --quota ${QUOTA_IN} -j ACCEPT

        # allow related outbound access limited by the quota
        nsenter --target "${PID}" -n iptables -A OUTPUT -p tcp --sport ${XINETD_LISTEN_PORT} -m state --state ESTABLISHED,RELATED -m quota --quota ${QUOTA_OUT} -j ACCEPT

        # enable the host to connect to rsyslog on the host
        #nsenter --target "${PID}" -n iptables -A OUTPUT -p tcp -m tcp --dst 172.17.42.1 --dport 514 -j ACCEPT

        # add iptables redirection rule
        iptables -t nat -A PREROUTING -i ${EXT_IFACE} -s "${REMOTE_HOST}" -p tcp -m tcp ! --dport ${XINETD_LISTEN_PORT} -j DNAT --to-destination "${CIP}"
        iptables -t nat -A POSTROUTING -j MASQUERADE
    else
        # start container if exited and grab the cid
        docker start "${CNM}" &> /dev/null
        CID=$(docker inspect --format '{{ .Id }}' "${CNM}")
        CIP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "${CID}")

        # add iptables redirection rule
        iptables -t nat -A PREROUTING -i ${EXT_IFACE} -s "${REMOTE_HOST}" -p tcp -m tcp ! --dport ${XINETD_LISTEN_PORT} -j DNAT --to-destination "${CIP}"
        iptables -t nat -A POSTROUTING -j MASQUERADE
    fi

    set +x
} &> /var/log/honeypot

# forward traffic to the container
exec socat stdin tcp:"${CIP}":${XINETD_LISTEN_PORT},retry=60

